added aws check

diff --git a/.github/workflows/dbBackup.yml b/.github/workflows/dbBackup.yml
--- a/.github/workflows/dbBackup.yml
+++ b/.github/workflows/dbBackup.yml
@@ -28,9 +28,14 @@ jobs:
           username: root
           key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
           script: |
-              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-              unzip awscliv2.zip
-              sudo ./aws/install
+              if ! command -v aws &> /dev/null; then
+                echo "AWS CLI not found. Installing..."
+                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+                unzip awscliv2.zip
+                sudo ./aws/install
+              else
+                echo "AWS CLI already installed. Skipping installation."
+              fi
 
       - name: rsync Scripts
         uses: burnett01/rsync-deployments@7.0.1
